### ISSUE TITLE
Coverting problem

### ISSUE THREAD

**Issue by Namoguru** [ksanaforge/tibetan#1]
![convert problem 2](https://cloud.githubusercontent.com/assets/7313201/7791385/f9d4e20c-02d1-11e5-9709-fc9a64d020f0.PNG)
1. So far I found only one error covert problem with letter which is red mark.

**Comment by exebook** [comment]
Can you please send me:
1) the dct file with the red character only
2) txt or html file with the same correct red character saved in utf-8 (not tibetdoc)

**Comment by Namoguru** [comment]
I have sent the file. Please check an email.

**Comment by exebook** [comment]
Thank you. I checked -- and it works. You can try for yourself:

http://rawgit.com/ksanaforge/tibetan/master/index.html

Or see my result:

http://exebook.github.io/tibet/With%20page%20break.dct.html

**Comment by Namoguru** [comment]
I think better try with this one སྠ་

**Comment by Namoguru** [comment]
Thanks
