### ISSUE TITLE
Only small size

### ISSUE THREAD

**Issue by Namoguru** [ksanaforge/tibetan#14]
![small size](https://cloud.githubusercontent.com/assets/7313201/8141837/2374025a-11a0-11e5-9a4a-81e52c711723.PNG)

I think all character is perfect. Only small size cannot covert which is very important

**Comment by exebook** [comment]
Send me this DCT please.

**Comment by exebook** [comment]
So what exactly is wrong? Small is not small enough?

**Comment by Namoguru** [comment]
When we use Tibetan font, if actual font size is 24, then we make small font size as 18

**Comment by Namoguru** [comment]
I didn't see any small font size convert from http://rawgit.com/ksanaforge/tibetan/master/index.html

**Comment by Namoguru** [comment]
I download from github and small size is perfect. Thank you very much. I think it is perfect now. Anyway, I will check more on Monday. Have a nice day or good night.
