### ISSUE TITLE
Page break problem

### ISSUE THREAD

**Issue by Namoguru** [ksanaforge/tibetan#3]
Page break in Tibetdoc doesn't covert. Better to covert into page break
![page break](https://cloud.githubusercontent.com/assets/7313201/7791521/1611b6be-02d4-11e5-97a3-1b4d8484c258.PNG)

**Comment by exebook** [comment]
I need a dct with page break

**Comment by Namoguru** [comment]
Khenpo Karma Namgyal  
Karma Lekshey Ling Institute
For Higher Buddhist Studies
Post Box No. 8435
Swoyambhu, Kathmandu, Nepal
Mobile: 00977-9818121555
www.leksheyling.netwww.dharmadownload.nethttp://words-of-karmapa.org/


Date: Tue, 26 May 2015 04:36:49 -0700

**Comment by Namoguru** [comment]
Send me your email address to send the file

**Comment by Namoguru** [comment]
Send me your email address to send the dct with page break

**Comment by exebook** [comment]
exebook at gmail

**Comment by exebook** [comment]
I have added the page break, maybe Yap needs to update the tool that you are using to reflect the change.

**Comment by Namoguru** [comment]
Thanks

**Comment by yapcheahshen** [comment]
Online Html converter should reflect changes, CTRL+F5 to clear browser
cache if not.
http://rawgit.com/ksanaforge/tibetan/master/index.html
從我的 HTC 寄出

----- Reply message -----
寄件者： "exebook" notifications@github.com
收件者： "ksanaforge/tibetan" tibetan@noreply.github.com
主旨： [tibetan] Page break problem (#3)
日期： 週四, 5月 28 日, 2015 年 3:27 上午

I have added the page break, maybe Yap needs to update the tool that you
are using to reflect the change.
