### ISSUE TITLE
need left or full justified

### ISSUE THREAD

**Issue by Namoguru** [ksanaforge/tibetan#4]
In html file, there is in center. We need either left of full justified.

![justified](https://cloud.githubusercontent.com/assets/7313201/7804510/ae378776-0396-11e5-8a08-0287bfbb2621.PNG)

**Comment by exebook** [comment]
I cannot reproduce this bug. Can you send me an example?
With my tests, justification works properly for all four cases: left, center, right, justify.

Please check my example file:
http://exebook.github.io/tibet/align.dct
http://exebook.github.io/tibet/align.dct.html

**Comment by Namoguru** [comment]
I have sent the file but http://exebook.github.io/tibet/align.dct.html is perfect
