### ISSUE TITLE
Coverting problem 2

### ISSUE THREAD

**Issue by Namoguru** [ksanaforge/tibetan#6]
Please check the hilight
![convert problem](https://cloud.githubusercontent.com/assets/7313201/7806275/8821b5aa-03b1-11e5-9189-ae9fd9e06805.PNG)

**Comment by yapcheahshen** [comment]
it seems like Unicode doesn't have a single code point for
SA+subjoined TA (0xF66 +0xF9F)

http://unicode.org/charts/PDF/U0F00.pdf

2015-05-26 14:15 GMT+08:00 Khenpo Namgyal notifications@github.com:

**Comment by Namoguru** [comment]
སྟྲ་་Can type in unicode

**Comment by exebook** [comment]
So what can I do about this?

**Comment by exebook** [comment]
I found that if you save those two incorect characters from TibetDoc.exe with File->Save As->Save as HTML->Unicode output: the result is: སཏྲ སྡྱི. 
Which means that even TibetDoc itself converts them incorrect.

**Comment by exebook** [comment]
I fixed the character སྟྲ་་. Can you please test?

I CANNOT fix the second wrong character because I have no correct Unicode for it.
