### ISSUE TITLE
i>> is also similar with tab

### ISSUE THREAD

**Issue by Namoguru** [ksanaforge/tibetan#9]
You can see the different between tab and space in the image. In dct files, we can see time to that one. Better we convert into space as tab.

![another tab](https://cloud.githubusercontent.com/assets/7313201/7860714/019caa34-057e-11e5-8e04-77d9d6b874e0.png)

**Comment by exebook** [comment]
How to type i>>?

**Comment by Namoguru** [comment]
Ctrl+n

**Comment by exebook** [comment]
What is the proper name for `i>>`
Do you want `i>>` just convert to TAB?

**Comment by Namoguru** [comment]
To space is better

**Comment by exebook** [comment]
But it looks much wider than space

**Comment by Namoguru** [comment]
Normally it works like numbering

**Comment by Namoguru** [comment]
I am now with mobile, I will show you sample tomorrow if you need it
